[package]
name = "esp32-landscape-weather-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
epd-waveshare = { git = "https://github.com/caemor/epd-waveshare", rev = "1244f035", features = ["graphics"] }
env_logger = "0.11.5"
log = "0.4.22"
mime = "0.3.17"
rand = "0.8.5"
image = "0.25.2"
anyhow = "1.0.89"
thiserror = "1.0.64"
embedded-graphics = "0.8.1"
