[package]
name = "landscape-weather-server"
version = "0.1.0"
repository = "https://github.com/martinohmann/esp32-landscape-weather"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
epd-waveshare = { git = "https://github.com/caemor/epd-waveshare", rev = "1244f035", features = ["graphics"] }
env_logger = "0.11.5"
log = "0.4.22"
mime = "0.3.17"
rand = "0.8.5"
image = "0.25.2"
anyhow = "1.0.89"
thiserror = "1.0.64"
embedded-graphics = "0.8.1"
monsoon = "0.1.1"
tower = { version = "0.5.1", features = ["limit", "util"] }
jiff = "0.1.13"
sun = "0.3.1"
config = "0.14.0"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
imageproc = "0.25.0"
actix-web-prom = "0.9.0"
prometheus = "0.13.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
