[package]
name = "esp32-landscape-weather-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
log = "0.4.22"
mime = "0.3.17"
rand = "0.8.5"
random = "0.14.0"
