version: '3.3'

services:
  weather-landscape:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - WEATHER_LATITUDE=${WEATHER_LATITUDE}
      - WEATHER_LONGITUDE=${WEATHER_LONGITUDE}
    networks:
      - weather-net
    user: "nobody"

networks:
  weather-net:
    driver: bridge
