---
name: Release Image

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"

concurrency:
  group: container-release
  cancel-in-progress: false

permissions:
  packages: write
  contents: read

jobs:
  release-images:
    uses: martinohmann/esp32-landscape-weather/.github/workflows/build-image.yaml@main
    secrets: inherit
    with:
      push: true
